name: Deploy Java Project to SparkedHost via SFTP

on:
  push:
    branches:
      - main  # Adjust if you want deployment from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to SparkedHost via SFTP

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install package  # Builds the JAR file with dependencies

      - name: Rename JAR for Deployment
        run: |
          mkdir -p deploy
          cp target/*-with-dependencies.jar deploy/ChisaTaki.jar  # Adjust this if your JAR name differs

      - name: Upload ChisaTaki.jar to SparkedHost via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "deploy/ChisaTaki.jar"
          target: "/path/on/server/ChisaTaki.jar"  # Update to your server path

